[package]
name = "wae-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
globset.workspace = true
fs2.workspace = true
ignore.workspace = true
serde.workspace = true
serde_json.workspace = true
wae-config = { path = "../config" }
wae-core = { path = "../core" }
wae-graph = { path = "../graph" }
wae-framework = { path = "../framework" }
wae-parser = { path = "../parser" }
wae-resolver = { path = "../resolver" }
wae-rules = { path = "../rules" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "incremental"
harness = false
